const SCREENS = {
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    HOME: 'HOME',
    PROFILE: 'PROFILE',
    SEARCH: 'SEARCH',
    MONTHLYREADING: 'MONTHLYREADING',
    READINGPROGRESSTRACKER: 'READINGPROGRESSTRACKER',
}

export default SCREENS